---
title: Midwest Access Coalition
timezone: America/Chicago
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
gems:
- jekyll-admin
exclude:
- config.ru
- Gemfile
- Gemfile.lock
- vendor
- Procfile
- Rakefile
email: info@midwestaccesscoalition.org
description: 'The Midwest Access Coalition provides accommodation and support to those
  who travel to Chicago to access a safe, legal abortion when prohibitive legislation
  limits access closer to home.

'
baseurl: 
url: http://midwestaccesscoalition.github.io
twitter_username: MidwestAccess
github_username: MidwestAccessCoalition
facebook_username: midwestaccesscoalition
upcoming_event: false
upcoming_event_eb_url: 
upcoming_event_description: ''
upcoming_event_img_path: img/upcoming-event-flyer.jpg
501_c_3_text_question: Is MAC a 501(c)3?
501_c_3_text_answer: Why yes! MAC is a 501(c)3 non-profit organization, and any donations
  will be tax-deductible.
markdown: kramdown
