# Site settings
title: Midwest Access Coalition
email: info@midwestaccesscoalition.org
description: > #
  The Midwest Access Coalition provides accommodation and support to those who travel to Chicago to access a safe, legal abortion when prohibitive legislation limits access closer to home.
baseurl:  # the subpath of your site, e.g. /blog/
url: "http://midwestaccesscoalition.github.io" # the base hostname & protocol for your site
twitter_username: MidwestAccess
github_username:  MidwestAccessCoalition
facebook_username: midwestaccesscoalition

timezone: America/Chicago

# pages_list:
# 	Donors: '/donors'
# 	Our Team: '/team'
# 	Announcements: '/announcements'
# 	Values & Goals: '/values-goals'

# Build settings
markdown: kramdown

collections:
  announcements:
    output: true
  resources:
    output: true
  connects:
    output: true